// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFWZTCZyEfWTeoOI-26j5Ta5kQ9-yMkaQ',
    appId: '1:460876811950:web:5937ffac523e7dbe82673f',
    messagingSenderId: '460876811950',
    projectId: 'flutterauth-efc10',
    authDomain: 'flutterauth-efc10.firebaseapp.com',
    storageBucket: 'flutterauth-efc10.appspot.com',
    measurementId: 'G-MC0S0S8VB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8rh7co5ClaZhkJ2xKRgaImbm7SABeU2k',
    appId: '1:460876811950:android:54b2d733aa2e5e7382673f',
    messagingSenderId: '460876811950',
    projectId: 'flutterauth-efc10',
    storageBucket: 'flutterauth-efc10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCReqHFdOYcaS3dRDJJMglWIj8x_cY3ewc',
    appId: '1:460876811950:ios:e8ad8d0897a1ec5282673f',
    messagingSenderId: '460876811950',
    projectId: 'flutterauth-efc10',
    storageBucket: 'flutterauth-efc10.appspot.com',
    iosBundleId: 'com.example.khannasir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCReqHFdOYcaS3dRDJJMglWIj8x_cY3ewc',
    appId: '1:460876811950:ios:abf8ceb517b3079582673f',
    messagingSenderId: '460876811950',
    projectId: 'flutterauth-efc10',
    storageBucket: 'flutterauth-efc10.appspot.com',
    iosBundleId: 'com.example.khannasir.RunnerTests',
  );
}
